#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          GRAFANA DASHBOARD - SETUP COMPLETE                    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ Metrics Infrastructure:"
echo "  • API exposing metrics on http://localhost:8080/metrics"
echo "  • Prometheus scraping targets: UP"
echo "  • Grafana dashboard configured with Prometheus datasource"
echo ""
echo "✓ Metrics Being Recorded:"
echo "  • snmpsim_labs_total - Total labs created (Counter)"
echo "  • snmpsim_labs_active - Currently active labs (Gauge)"
echo "  • snmpsim_packets_total - API requests/packets processed (Counter)"
echo "  • snmpsim_failures_total - Operation failures (Counter)"
echo ""
echo "✓ Dashboard Panels:"
echo "  1. Total Labs Created - Shows cumulative lab creation count"
echo "  2. SNMP Failures - Shows error metrics"
echo "  3. SNMP Operation Latency - Shows request latency"
echo "  4. Active Labs - Shows currently running labs"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🎨 VIEW YOUR DASHBOARD"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "1. Open http://localhost:3000 in your browser"
echo ""
echo "2. Login with:"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "3. Navigate to:"
echo "   Dashboards → SNMP Simulator Metrics"
echo ""
echo "4. You will see:"
echo "   • Total Labs Created: 10"
echo "   • Active Labs: 10"
echo "   • SNMP Failures: (empty if no errors)"
echo "   • API Packet Traffic: Multiple GET requests"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "📊 GENERATE MORE DATA"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "To generate additional test metrics:"
echo ""
echo "  # Create more labs and API traffic"
echo "  ./generate-test-metrics.sh"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "🔍 VERIFY METRICS ARE FLOWING"
echo "───────────────────────────────────────────────────────────────"
echo ""
echo "Check metrics endpoint:"
echo "  curl http://localhost:8080/metrics | grep snmpsim"
echo ""
echo "Query Prometheus:"
echo "  curl 'http://localhost:9091/api/v1/query?query=snmpsim_labs_total'"
echo ""
echo "───────────────────────────────────────────────────────────────"
echo "✨ DASHBOARD READY - REFRESH TO VIEW LIVE DATA"
echo "───────────────────────────────────────────────────────────────"
